"""add failed_login_count and locked_until to admins

Revision ID: 3393d4b194d1
Revises: 525e44b0c237
Create Date: 2026-03-11 12:20:12.970782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3393d4b194d1'
down_revision: Union[str, Sequence[str], None] = '525e44b0c237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('failed_login_count', sa.Integer(), nullable=False))
    op.add_column('admins', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'locked_until')
    op.drop_column('admins', 'failed_login_count')
    # ### end Alembic commands ###
