"""add token_blocklist and admin lockout columns

Revision ID: 42ad52c4fa10
Revises: 50a97f146fa2
Create Date: 2026-03-30 14:51:59.809079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ad52c4fa10'
down_revision: Union[str, Sequence[str], None] = '50a97f146fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
