"""add_images_column_to_products

Revision ID: 5833797b82b0
Revises: 8d7e462a2fa1
Create Date: 2026-04-06 02:12:10.740369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5833797b82b0'
down_revision: Union[str, Sequence[str], None] = '8d7e462a2fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocklist')
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'images')
    op.create_table('token_blocklist',
    sa.Column('jti', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('jti'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
