"""add_category_fk_and_filter_columns_to_products

Revision ID: f020dea7e6f8
Revises: 611f47e824f5
Create Date: 2026-04-21 14:35:31.943623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f020dea7e6f8'
down_revision: Union[str, Sequence[str], None] = '611f47e824f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('year_min', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('year_max', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('engine_type', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('model_type', sa.String(length=100), nullable=True))
    op.alter_column('products', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_engine_type'), 'products', ['engine_type'], unique=False)
    op.create_index(op.f('ix_products_model_type'), 'products', ['model_type'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_year_max'), 'products', ['year_max'], unique=False)
    op.create_index(op.f('ix_products_year_min'), 'products', ['year_min'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_year_min'), table_name='products')
    op.drop_index(op.f('ix_products_year_max'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_model_type'), table_name='products')
    op.drop_index(op.f('ix_products_engine_type'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.alter_column('products', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_column('products', 'model_type')
    op.drop_column('products', 'engine_type')
    op.drop_column('products', 'year_max')
    op.drop_column('products', 'year_min')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
